# Generated by Django 5.1.15 on 2026-05-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('landing', 'Landing / Home'), ('about', 'About'), ('licenses', 'Licenses'), ('sitemap', 'Sitemap')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'static page',
                'verbose_name_plural': 'static pages',
                'db_table': 'pages_staticpage',
            },
        ),
        migrations.CreateModel(
            name='SystemFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'system flag',
                'verbose_name_plural': 'system flags',
                'db_table': 'pages_systemflag',
                'ordering': ['key'],
            },
        ),
    ]
