# Generated by Django 5.1.15 on 2026-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
