/**
 * HomePage (/home) — authenticated E2E tests.
 *
 * Requires: ./e2e/.auth/session.json (generated by e2e:auth-setup script)
 *
 * Tests:
 *  - Feed renders post cards with correct data
 *  - Post author names in feed never show raw Clerk IDs
 *  - Infinite scroll trigger element exists
 *  - Page structure is correct
 */
import { test, expect } from '@playwright/test';
import { mockBackendApi } from './helpers/api-mock';
import {
  CLERK_ID_PATTERN,
  MOCK_FEED_RESPONSE,
  MOCK_PROFILE,
  MOCK_AUTHOR_CLERK_USERNAME,
  MOCK_AUTHOR_CLERK_DISPLAY_NAME,
  makeMockPost,
} from './mock-data';
import { expectNoClerkIds } from './helpers/assertions';

test.use({ storageState: './e2e/.auth/session.json' });

test.describe('HomePage (/home) — authenticated', () => {
  test.beforeEach(async ({ page }) => {
    await mockBackendApi(page, {
      feed: MOCK_FEED_RESPONSE,
      me: MOCK_PROFILE,
    });
    await page.goto('/home');
    await page.waitForTimeout(2000);
  });

  // ── Feed rendering ───────────────────────────────────────────────────────────

  test('renders the home page without crashing', async ({ page }) => {
    await expect(page).toHaveURL(/\/home/);
    const body = page.locator('body');
    await expect(body).toBeVisible();
  });

  test('shows post cards from the feed', async ({ page }) => {
    // Wait for posts to appear
    const postCards = page.locator('.post, [class*="post-card"], [class*="post_"]');
    await expect(postCards.first()).toBeVisible({ timeout: 10_000 });
  });

  test('post cards show author names', async ({ page }) => {
    const authorEls = page.locator('.author-username');
    const count = await authorEls.count();
    if (count > 0) {
      await expect(authorEls.first()).toBeVisible();
      const text = await authorEls.first().innerText();
      expect(text.length).toBeGreaterThan(0);
    }
  });

  // ── Clerk ID regression in feed ──────────────────────────────────────────────

  test('no raw Clerk IDs visible in feed authors', async ({ page }) => {
    const authorEls = page.locator('.author-username');
    const count = await authorEls.count();
    for (let i = 0; i < count; i++) {
      const text = await authorEls.nth(i).innerText();
      expect(text, `Author ${i} shows raw Clerk ID: ${text}`).not.toMatch(
        CLERK_ID_PATTERN,
      );
    }
  });

  test('no raw Clerk IDs anywhere on home page', async ({ page }) => {
    await expectNoClerkIds(page);
  });

  // ── Feed with Clerk ID authors ────────────────────────────────────────────────

  test('feed with all-Clerk-ID authors shows no raw IDs in UI', async ({
    page,
  }) => {
    const clerkIdFeed = {
      results: [
        makeMockPost({ id: 10, slug: 'c1', author: MOCK_AUTHOR_CLERK_USERNAME }),
        makeMockPost({ id: 11, slug: 'c2', author: MOCK_AUTHOR_CLERK_DISPLAY_NAME }),
      ],
      next: null,
      count: 2,
    };
    await mockBackendApi(page, {
      feed: clerkIdFeed,
      posts: clerkIdFeed,
      me: MOCK_PROFILE,
    });
    await page.goto('/home');
    await page.waitForTimeout(3000);

    await expectNoClerkIds(page);
  });

  // ── Infinite scroll ───────────────────────────────────────────────────────────

  test('infinite scroll sentinel element exists', async ({ page }) => {
    // There should be a scroll trigger / sentinel at the bottom of the feed
    const sentinel = page.locator(
      '[class*="sentinel"], [class*="scroll-trigger"], [class*="load-more"], [data-testid="sentinel"]',
    );
    // If the app uses IntersectionObserver-based infinite scroll, this should exist
    const count = await sentinel.count();
    if (count > 0) {
      await expect(sentinel.first()).toBeAttached();
    }
    // If no sentinel found, at least verify no JS error crashed the page
    // by confirming post content is visible
    const posts = page.locator('.post, [class*="post-card"]');
    expect(await posts.count()).toBeGreaterThan(0);
  });

  // ── Page title and navigation ─────────────────────────────────────────────────

  test('page title is not empty', async ({ page }) => {
    const title = await page.title();
    expect(title.length).toBeGreaterThan(0);
  });

  test('navigation bar is visible', async ({ page }) => {
    const nav = page.locator('nav, header, .navigation, .nav-bar');
    await expect(nav.first()).toBeVisible();
  });

  // ── Responsive layout ─────────────────────────────────────────────────────────

  test('home page renders on mobile (375px)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/home');
    await page.waitForTimeout(2000);

    // No horizontal overflow
    const scrollWidth = await page.evaluate(
      () => document.documentElement.scrollWidth,
    );
    const clientWidth = await page.evaluate(
      () => document.documentElement.clientWidth,
    );
    expect(scrollWidth).toBeLessThanOrEqual(clientWidth + 5);
  });
});
