/**
 * ProfilePage (/profile) — authenticated E2E tests.
 *
 * Requires: ./e2e/.auth/session.json (generated by e2e:auth-setup script)
 *
 * Tests:
 *  - Profile page renders correctly
 *  - Display name and @username never show raw Clerk internal IDs
 *  - Even when /me/ API returns Clerk ID in username/display_name fields
 */
import { test, expect } from '@playwright/test';
import { mockBackendApi } from './helpers/api-mock';
import {
  CLERK_ID_PATTERN,
  MOCK_PROFILE,
  MOCK_PROFILE_CLERK_ID,
} from './mock-data';
import {
  expectNoClerkIds,
  expectNoClerkIdIn,
} from './helpers/assertions';

// Use the pre-authenticated storageState set in playwright.config.ts `authenticated` project
test.use({ storageState: './e2e/.auth/session.json' });

test.describe('ProfilePage (/profile) — authenticated', () => {
  // ── Happy path ───────────────────────────────────────────────────────────────

  test('renders profile page without crashing', async ({ page }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE });
    await page.goto('/profile');

    // Should stay on /profile (not redirect to /auth)
    await expect(page).toHaveURL(/\/profile/);
    await page.waitForTimeout(2000);

    // Page has content
    const body = page.locator('body');
    await expect(body).toBeVisible();
  });

  test('displays user display name', async ({ page }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE });
    await page.goto('/profile');
    await page.waitForSelector('.pp-displayname', { timeout: 15_000 });

    const displayName = page.locator('.pp-displayname');
    await expect(displayName).toBeVisible();
    await expect(displayName).toContainText('Slop Master');
  });

  test('displays @username with @ prefix', async ({ page }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE });
    await page.goto('/profile');
    await page.waitForSelector('.pp-username', { timeout: 15_000 });

    const username = page.locator('.pp-username');
    await expect(username).toBeVisible();
    // Should start with @
    const text = await username.innerText();
    expect(text).toMatch(/^@/);
  });

  // ── Clerk ID regression — display name ────────────────────────────────────

  test('display name never shows raw Clerk ID even when API returns one', async ({
    page,
  }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE_CLERK_ID });
    await page.goto('/profile');
    await page.waitForSelector('.pp-displayname, .pp-username', {
      timeout: 15_000,
    });

    // The display name must NOT be a Clerk internal ID
    const displayName = page.locator('.pp-displayname');
    if (await displayName.count() > 0) {
      const text = await displayName.innerText();
      expect(text).not.toMatch(CLERK_ID_PATTERN);
      // Should show a fallback like "ANON" or something readable
      expect(text.length).toBeGreaterThan(0);
    }
  });

  test('@username never shows raw Clerk ID even when API returns one', async ({
    page,
  }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE_CLERK_ID });
    await page.goto('/profile');
    await page.waitForSelector('.pp-username', { timeout: 15_000 });

    const username = page.locator('.pp-username');
    if (await username.count() > 0) {
      await expectNoClerkIdIn(page, '.pp-username');
    }
  });

  test('no raw Clerk IDs anywhere on profile page', async ({ page }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE_CLERK_ID });
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    await expectNoClerkIds(page);
  });

  // ── Profile structure ────────────────────────────────────────────────────────

  test('profile page has a single H1', async ({ page }) => {
    await mockBackendApi(page, { me: MOCK_PROFILE });
    await page.goto('/profile');
    await page.waitForTimeout(2000);

    const h1s = page.locator('h1');
    const count = await h1s.count();
    expect(count).toBeLessThanOrEqual(1);
  });

  test('profile page does not show console errors', async ({ page }) => {
    const errors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        const text = msg.text();
        // Ignore known external noise
        const ignored =
          text.includes('clerk') ||
          text.includes('Clerk') ||
          text.includes('CORS') ||
          text.includes('favicon') ||
          text.includes('ResizeObserver');
        if (!ignored) errors.push(text);
      }
    });

    await mockBackendApi(page, { me: MOCK_PROFILE });
    await page.goto('/profile');
    await page.waitForTimeout(3000);

    expect(errors).toHaveLength(0);
  });
});
